ygdance:
  action_scale:
    - 0.333
    - 0.333
    - 0.359
    - 0.333
    - 0.333
    - 0.124
    - 0.124
    - 0.289
    - 0.289
    - 0.124
    - 0.124
    - 0.289
    - 0.289
    - 0.124
    - 0.124
    - 0.798
    - 0.798
    - 0.206
    - 0.206
    - 0.798
    - 0.798
    - 0.206
    - 0.206
  default_joint_pos:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.149
    - -0.149
    - 0.262
    - -0.262
    - 0.322
    - 0.322
    - 0.0
    - 0.0
    - -0.172
    - -0.172
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  joint_damping:
    - 4.778
    - 4.778
    - 3.322
    - 4.778
    - 4.778
    - 3.217
    - 3.217
    - 4.998
    - 4.998
    - 3.217
    - 3.217
    - 4.998
    - 4.998
    - 3.217
    - 3.217
    - 1.744
    - 1.744
    - 1.93
    - 1.93
    - 1.744
    - 1.744
    - 1.93
    - 1.93
  joint_names:
    - l_leg_hip_yaw_joint
    - r_leg_hip_yaw_joint
    - waist_yaw_joint
    - l_leg_hip_roll_joint
    - r_leg_hip_roll_joint
    - l_arm_shoulder_pitch_joint
    - r_arm_shoulder_pitch_joint
    - l_leg_hip_pitch_joint
    - r_leg_hip_pitch_joint
    - l_arm_shoulder_roll_joint
    - r_arm_shoulder_roll_joint
    - l_leg_knee_joint
    - r_leg_knee_joint
    - l_arm_shoulder_yaw_joint
    - r_arm_shoulder_yaw_joint
    - l_leg_ankle_pitch_joint
    - r_leg_ankle_pitch_joint
    - l_arm_elbow_pitch_joint
    - r_arm_elbow_pitch_joint
    - l_leg_ankle_roll_joint
    - r_leg_ankle_roll_joint
    - l_arm_elbow_yaw_joint
    - r_arm_elbow_yaw_joint
  joint_stiffness:
    - 60.042
    - 60.042
    - 41.75
    - 60.042
    - 60.042
    - 40.426
    - 40.426
    - 86.633
    - 86.633
    - 40.426
    - 40.426
    - 86.633
    - 86.633
    - 40.426
    - 40.426
    - 21.919
    - 21.919
    - 24.256
    - 24.256
    - 21.919
    - 21.919
    - 24.256
    - 24.256
  control:
    decimation: 10
  normalization:
    clip_scales:
      clip_observations: 18.0
      clip_actions: 18.0
  size:
    actions_size: 23
    observations_size: 124
    stack_size: 5
  axis_mappings:
    scalez: 1.0
    scalex: 0.8
    scaley: 0.0
dance:
  action_scale:
    - 0.333
    - 0.333
    - 0.359
    - 0.333
    - 0.333
    - 0.124
    - 0.124
    - 0.289
    - 0.289
    - 0.124
    - 0.124
    - 0.289
    - 0.289
    - 0.124
    - 0.124
    - 0.798
    - 0.798
    - 0.206
    - 0.206
    - 0.798
    - 0.798
    - 0.206
    - 0.206
  default_joint_pos:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.149
    - -0.149
    - 0.262
    - -0.262
    - 0.322
    - 0.322
    - 0.0
    - 0.0
    - -0.172
    - -0.172
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  joint_damping:
    - 4.778
    - 4.778
    - 3.322
    - 4.778
    - 4.778
    - 3.217
    - 3.217
    - 4.998
    - 4.998
    - 3.217
    - 3.217
    - 4.998
    - 4.998
    - 3.217
    - 3.217
    - 1.744
    - 1.744
    - 1.93
    - 1.93
    - 1.744
    - 1.744
    - 1.93
    - 1.93
  joint_names:
    - l_leg_hip_yaw_joint
    - r_leg_hip_yaw_joint
    - waist_yaw_joint
    - l_leg_hip_roll_joint
    - r_leg_hip_roll_joint
    - l_arm_shoulder_pitch_joint
    - r_arm_shoulder_pitch_joint
    - l_leg_hip_pitch_joint
    - r_leg_hip_pitch_joint
    - l_arm_shoulder_roll_joint
    - r_arm_shoulder_roll_joint
    - l_leg_knee_joint
    - r_leg_knee_joint
    - l_arm_shoulder_yaw_joint
    - r_arm_shoulder_yaw_joint
    - l_leg_ankle_pitch_joint
    - r_leg_ankle_pitch_joint
    - l_arm_elbow_pitch_joint
    - r_arm_elbow_pitch_joint
    - l_leg_ankle_roll_joint
    - r_leg_ankle_roll_joint
    - l_arm_elbow_yaw_joint
    - r_arm_elbow_yaw_joint
  joint_stiffness:
    - 60.042
    - 60.042
    - 41.75
    - 60.042
    - 60.042
    - 40.426
    - 40.426
    - 86.633
    - 86.633
    - 40.426
    - 40.426
    - 86.633
    - 86.633
    - 40.426
    - 40.426
    - 21.919
    - 21.919
    - 24.256
    - 24.256
    - 21.919
    - 21.919
    - 24.256
    - 24.256
  control:
    decimation: 10
  normalization:
    clip_scales:
      clip_observations: 18.0
      clip_actions: 18.0

  size:
    actions_size: 23
    observations_size: 124
    stack_size: 5
  axis_mappings:
    scalez: 1.0
    scalex: 0.8
    scaley: 0.0
run:
  action_scale:
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
  default_joint_pos:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.149
    - -0.149
    - 0.262
    - -0.262
    - 0.322
    - 0.322
    - 0.0
    - 0.0
    - -0.172
    - -0.172
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  joint_damping:
    - 4.0
    - 4.0
    - 4.0
    - 4.0
    - 4.0
    - 4.021
    - 4.021
    - 5.0
    - 5.0
    - 4.021
    - 4.021
    - 5.0
    - 5.0
    - 4.021
    - 4.021
    - 2.0
    - 2.0
    - 4.021
    - 4.021
    - 2.0
    - 2.0
    - 4.021
    - 4.021
  joint_names:
    - l_leg_hip_yaw_joint
    - r_leg_hip_yaw_joint
    - waist_yaw_joint
    - l_leg_hip_roll_joint
    - r_leg_hip_roll_joint
    - l_arm_shoulder_pitch_joint
    - r_arm_shoulder_pitch_joint
    - l_leg_hip_pitch_joint
    - r_leg_hip_pitch_joint
    - l_arm_shoulder_roll_joint
    - r_arm_shoulder_roll_joint
    - l_leg_knee_joint
    - r_leg_knee_joint
    - l_arm_shoulder_yaw_joint
    - r_arm_shoulder_yaw_joint
    - l_leg_ankle_pitch_joint
    - r_leg_ankle_pitch_joint
    - l_arm_elbow_pitch_joint
    - r_arm_elbow_pitch_joint
    - l_leg_ankle_roll_joint
    - r_leg_ankle_roll_joint
    - l_arm_elbow_yaw_joint
    - r_arm_elbow_yaw_joint
  joint_stiffness:
    - 80.0
    - 80.0
    - 70.0
    - 80.0
    - 80.0
    - 31.583
    - 31.583
    - 120.0
    - 120.0
    - 31.583
    - 31.583
    - 150.0
    - 150.0
    - 31.583
    - 31.583
    - 30.0
    - 30.0
    - 31.583
    - 31.583
    - 30.0
    - 30.0
    - 31.583
    - 31.583
  control:
    decimation: 10
  normalization:
    clip_scales:
      clip_observations: 18.0
      clip_actions: 18.0

  size:
    actions_size: 23
    observations_size: 78
    stack_size: 5
  axis_mappings:
    scalez: 1.0
    scalex: 2.0
    scaley: 0.5
walk:
  action_scale:
    - 0.213
    - 0.213
    - 0.213
    - 0.213
    - 0.185
    - 0.185
    - 0.185
    - 0.185
    - 0.511
    - 0.511
    - 0.511
    - 0.511
  default_joint_pos:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -0.149
    - -0.149
    - 0.322
    - 0.322
    - -0.172
    - -0.172
    - 0.0
    - 0.0
  joint_damping:
    - 4.479
    - 4.479
    - 4.479
    - 4.479
    - 4.74
    - 4.74
    - 4.74
    - 4.74
    - 2.18
    - 2.18
    - 2.18
    - 2.18
  joint_names:
    - l_leg_hip_yaw_joint
    - r_leg_hip_yaw_joint
    - l_leg_hip_roll_joint
    - r_leg_hip_roll_joint
    - l_leg_hip_pitch_joint
    - r_leg_hip_pitch_joint
    - l_leg_knee_joint
    - r_leg_knee_joint
    - l_leg_ankle_pitch_joint
    - r_leg_ankle_pitch_joint
    - l_leg_ankle_roll_joint
    - r_leg_ankle_roll_joint
  joint_stiffness:
    - 93.816
    - 93.816
    - 93.816
    - 93.816
    - 135.364
    - 135.364
    - 135.364
    - 135.364
    - 34.248
    - 34.248
    - 34.248
    - 34.248
  control:
    decimation: 10
    cycle_time: 4.0
  normalization:
    clip_scales:
      clip_observations: 18.0
      clip_actions: 18.0

  size:
    actions_size: 12
    observations_size: 45
    stack_size: 5
  axis_mappings:
    scalez: 0.8
    scalex: 1.0
    scaley: 0.5
